# Generated by Django 5.2.1 on 2025-05-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_schoolfeepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfeepayment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
