# Generated by Django 5.2.1 on 2025-05-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_schoolfeepayment_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfeepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
