# Generated by Django 5.2.1 on 2025-05-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_schoolfeepayment_amount_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolFeePayment',
        ),
    ]
