# Generated by Django 5.2.1 on 2025-05-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_student_has_paid_fees_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='has_paid_fees',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
