# Generated by Django 5.2.1 on 2025-05-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_student_has_paid_fees_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_paid_school_fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
