# Generated by Django 5.2.1 on 2025-06-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_lecturer_course_lecturer_registeredcourse_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='department',
        ),
    ]
