# Generated by Django 5.2.1 on 2025-06-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_remove_lecturer_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredcourse',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturer',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
