# Generated by Django 5.2.1 on 2025-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_remove_registeredcourse_lecturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
