# Generated by Django 5.2.1 on 2025-06-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_course_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
