# Generated by Django 5.2.1 on 2025-06-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_course_schedule_course_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.CharField(blank=True, null=True),
        ),
    ]
