# Generated by Django 5.2.1 on 2025-06-05 12:04

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_course_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='schedule',
        ),
        migrations.AddField(
            model_name='course',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
