# Generated by Django 5.2.1 on 2025-06-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_remove_course_schedule_course_days_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
