# Generated by Django 5.2.1 on 2025-06-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
