# Generated by Django 5.2.1 on 2025-06-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_alter_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(blank=True, choices=[('08:00AM', '08:00 AM'), ('09:00AM', '09:00 AM'), ('10:00AM', '10:00 AM'), ('11:00AM', '11:00 AM'), ('12:00PM', '12:00 PM'), ('13:00PM', '01:00 PM'), ('14:00PM', '02:00 PM'), ('15:00PM', '03:00 PM'), ('16:00PM', '04:00 PM'), ('17:00PM', '05:00 PM')], max_length=10, null=True),
        ),
    ]
