# Generated by Django 5.2.1 on 2025-06-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_alter_course_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='number',
            field=models.CharField(unique=True),
        ),
    ]
