# Generated by Django 5.2.1 on 2025-06-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_alter_year_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
