# Generated by Django 5.2.1 on 2025-06-15 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_alter_student_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='timetables/')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='portal.school')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='portal.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='portal.semester')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='portal.year')),
            ],
        ),
    ]
