# Generated by Django 5.2.1 on 2025-06-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='year',
        ),
    ]
