# Generated by Django 5.2.1 on 2025-06-16 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_remove_timetable_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='School',
        ),
    ]
