# Generated by Django 5.2.1 on 2025-06-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_remove_timetable_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('department', 'semester')},
        ),
    ]
