# Generated by Django 5.2.1 on 2025-06-16 12:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_alter_timetable_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.PositiveIntegerField(help_text='Amount in kobo')),
                ('status', models.CharField(default='success', max_length=20)),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(default='School Fees', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to='portal.student')),
            ],
        ),
    ]
