# Generated by Django 5.2.1 on 2025-06-17 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_paymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssce_result', models.FileField(blank=True, null=True, upload_to='ssce_results/')),
                ('jamb_result', models.FileField(blank=True, null=True, upload_to='jamb_results/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to='portal.student')),
            ],
        ),
    ]
