# Generated by Django 5.2.1 on 2025-06-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_screening_passed_screening'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
