# Generated by Django 5.2.1 on 2025-06-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_screening_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='student_name',
        ),
    ]
