# Generated by Django 5.2.1 on 2025-06-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_remove_screening_passed_screening_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_paid_acceptance_fee',
            field=models.BooleanField(default=False),
        ),
    ]
