# Generated by Django 5.2.1 on 2025-06-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_student_has_paid_acceptance_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(choices=[('School Fees', 'School Fees'), ('Acceptance Fees', 'Acceptance Fees')], default='School Fees', max_length=50),
        ),
    ]
