# Generated by Django 5.2.1 on 2025-06-28 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_alter_paymenthistory_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.semester'),
            preserve_default=False,
        ),
    ]
