# Generated by Django 5.2.1 on 2025-06-29 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_paymenthistory_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.year'),
        ),
    ]
