# Generated by Django 5.2.1 on 2025-06-29 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_paymenthistory_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='year',
        ),
    ]
