# Generated by Django 5.2.1 on 2025-06-29 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_remove_paymenthistory_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.year'),
            preserve_default=False,
        ),
    ]
