# Generated by Django 5.2.1 on 2025-07-05 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_paymenthistory_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.semester'),
        ),
    ]
