# Generated by Django 5.2.1 on 2025-07-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
