# Generated by Django 5.2.1 on 2025-07-22 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0049_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='semester',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='portal.semester'),
        ),
    ]
