# Generated by Django 5.2.1 on 2025-07-22 14:47

import django.db.models.deletion
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0050_alter_application_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.AlterField(
            model_name='application',
            name='semester',
            field=models.ForeignKey(default=portal.models.get_default_semester, on_delete=django.db.models.deletion.CASCADE, to='portal.semester'),
        ),
    ]
