# Generated by Django 5.2.1 on 2025-07-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0051_remove_application_user_alter_application_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='academic_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.academicsession'),
        ),
    ]
