# Generated by Django 5.2.1 on 2025-07-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0054_screningofficer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screningofficer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='screningofficer',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdmissionOfficer',
        ),
        migrations.DeleteModel(
            name='ScreningOfficer',
        ),
    ]
