# Generated by Django 5.2.1 on 2025-07-23 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0057_rename_userprofile_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.school'),
            preserve_default=False,
        ),
    ]
