# Generated by Django 5.2.1 on 2025-07-24 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('portal', '0059_staffprofile_first_name_staffprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='group',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
